"""Add user_id and username to Supervisor and Representative models

Revision ID: b23abde01b88
Revises: 
Create Date: 2024-12-19 21:31:35.012217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23abde01b88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('representatives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))  # تعديل لجعلها قابلة لـ NULL
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))  # تعديل لجعلها قابلة لـ NULL

    with op.batch_alter_table('supervisors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))  # تعديل لجعلها قابلة لـ NULL
        batch_op.add_column(sa.Column('username', sa.String(length=100), nullable=True))  # تعديل لجعلها قابلة لـ NULL

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supervisors', schema=None) as batch_op:
        batch_op.drop_column('username')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('representatives', schema=None) as batch_op:
        batch_op.drop_column('username')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
